### PR TITLE
Added KVFilter, Atomicswitch start

### PR DESCRIPTION
**Pull request by przygienda**
per previous pull added KVFilter, reordered things  for performance from experience here (you want KVFilter & LevelFilter _before_ Async)

Atomicswitch integrated, control will still need exposure, thinking about it.

### CODE REVIEW

**Comment by sile** [comment]
I think that it is better to divide the feature related to `AtomicSwitch` into a different PR.
`KVFilter` related code seems has no problem, so it will be possible to be merged sooner if it is separated from the `AtomicSwitch` code.

**Comment by przygienda** [comment]
removed atomicswitch for this PR ...

**Comment by sile** [comment]
Thanks, but some `AtomicSwitch` related code are remaining (e.g., https://github.com/sile/sloggers/pull/13/files#diff-6d00071c5cb83f348e478f2a87d45999R122 ).

**Comment by przygienda** [comment]
sorry, probably forgot to push ...

**Comment by sile** [comment]
Thanks!
I will merge this PR.

**Pull request merged**
