### PR TITLE
Add basic log file rotation functionality

### PR DESCRIPTION
**Pull request by sile**
Add `rotate_size` and `rotate_keep` options to `FileLoggerBuilder` and `FileLoggerConfig` for supporting basic log file rotation.

Related Issue: https://github.com/sile/sloggers/issues/12

### CODE REVIEW

**Comment by przygienda** [comment]
Looked over, cool. Are you willing to add compression on rotation as option (i.e. the old file is moved to a new name and compressed into .gz?)  interesting question being how the compression should be forked? thread? then we'll have lifetime issues I think. spawning a process? tad heavy ... Some kind of worker queue?

**Comment by sile** [comment]
> Are you willing to add compression on rotation as option ...

I would like to keep this PR simple, but I will consider it a bit.

**Comment by przygienda** [comment]
cool, willing to help if you attack that ... think through design first &
whether you want to go there ...

slog is a professional quality logger and that take it a notch higher up
again IMO ... Alternately, we could implement a log-rotating-copressing
drain and take the whole thing out of sloggers if you prefer and let
sloggers use that just like it uses KVFilter now ...

**Comment by sile** [comment]
Thank you for your comments. > @przygienda 

I prefer to use threads for compressing log files. And  I added rotated log file compression option at https://github.com/sile/sloggers/pull/14/commits/049b6cf3ffcf6ac6ed53d8ab3332c9c665045cf1. 

>  Alternately, we could implement a log-rotating-copressing drain and take the whole thing out of sloggers if you prefer and let sloggers use that just like it uses KVFilter now ...

If you want a more advanced implementation (or options) than https://github.com/sile/sloggers/pull/14/commits/049b6cf3ffcf6ac6ed53d8ab3332c9c665045cf1, it seems better to implement this feature on another crate like `slog-kvfilter`.

**Comment by przygienda** [comment]
so, that's getting pulled up? looks good and useful to me ...

**Comment by sile** [comment]
>  looks good and useful to me 

I see. I will merge this PR after conflicts are resolved.

**Pull request merged**
